'use strict';

/**
 * Cross-implementation check: Node hashOnly must match Java HashOnlyRecord
 * for every line in fixtures/hash-samples.jsonl (generated by Java HashSampleGenerator).
 */

const fs = require('fs');
const path = require('path');
const { test } = require('node:test');
const assert = require('node:assert');

const hashOnly = require('../src/services/hashOnly');

const FIXTURE = path.join(__dirname, 'fixtures', 'hash-samples.jsonl');

test('hash-cross-impl: 20/20 fixtures match Java HashOnlyRecord', () => {
  let raw;
  try {
    raw = fs.readFileSync(FIXTURE, 'utf8');
  } catch (e) {
    assert.fail(
      'Missing test/fixtures/hash-samples.jsonl. From api-gateway run: npm run generate-hash-samples'
    );
  }

  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
  assert.strictEqual(lines.length, 20, 'expected exactly 20 samples');

  for (let i = 0; i < lines.length; i++) {
    const row = JSON.parse(lines[i]);
    const {
      caseId,
      caseJson,
      aggregateHash,
      examiner,
      createdAt,
      expectedIndexHash,
      expectedRecordHash
    } = row;

    const idx = hashOnly.computeIndexHash(caseId);
    const rec = hashOnly.computeRecordHash(caseId, caseJson, aggregateHash, examiner, createdAt);

    assert.strictEqual(
      idx,
      expectedIndexHash,
      `sample ${i}: index hash mismatch for caseId=${JSON.stringify(caseId)}`
    );
    assert.strictEqual(
      rec,
      expectedRecordHash,
      `sample ${i}: record hash mismatch for caseId=${JSON.stringify(caseId)}`
    );

    const full = JSON.stringify({
      case_id: caseId,
      case_json: caseJson,
      aggregate_hash: aggregateHash,
      examiner,
      created_at: createdAt
    });
    assert.strictEqual(hashOnly.computeRecordHashFromJson(full), expectedRecordHash);
  }
});
